polls/urls.py
from django.urls import path
from . import views as v
from django.contrib.auth import views


app_name = 'polls'
urlpatterns = [
    path('', v.IndexView.as_view(), name='index'),
    path('<int:pk>/', v.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', v.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', v.vote, name='vote'),
    path('<int:question_id>/delete/', v.delete, name='delete'),
    path('login/', v.LoginView.as_view(), name='login'),
    path('logout/', v.LogoutView.as_view(), name='logout'),
    path('registration/', v.RegistrationView.as_view(), name='registration'),
    path('account/', v.account, name='account'),
    path('account/<int:user_id>/', v.user_account, name='user_account'),
    path('account/<int:user_id>/edit/', v.edit_account, name='edit'),
    path('account/<int:user_id>/create/', v.create, name='create'),
]

webapp/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.main),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    bio = models.CharField(max_length=100, default="")

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)


class Question(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms


class RegistrationForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    first_name = forms.CharField()
    last_name = forms.CharField()


class EditAccountForm(forms.Form):
    username = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    bio = forms.CharField(required=False)


class CreatePollForm(forms.Form):
    question = forms.CharField(required=True)
    choice1 = forms.CharField(required=True)
    choice2 = forms.CharField(required=True)
    choice3 = forms.CharField(required=False)
    choice4 = forms.CharField(required=False)
    choice5 = forms.CharField(required=False)

polls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from .models import Question, Choice, Profile
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .forms import RegistrationForm, EditAccountForm, CreatePollForm
from django.contrib.auth import views


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:10]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class RegistrationView(generic.FormView):
    template_name = 'registration/registration.html'

    def dispatch(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST)
        if request.method == 'POST':
            if form.is_valid():
                username = form.cleaned_data['username']
                email = form.cleaned_data['email']
                password1 = form.cleaned_data['password']
                password2 = form.cleaned_data['confirm_password']
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                if password1 == password2:
                    user = User.objects.create_user(username, email, password1)
                    user.first_name = first_name
                    user.last_name = last_name
                    user.save()
                    Profile.objects.create(user=user)
                    return redirect('/polls/login')

        return render(request, self.template_name, {'form': form})


class LoginView(views.LoginView):
    template_name = 'registration/login.html'


class LogoutView(views.LogoutView):
    template_name = 'registration/logout.html'


@login_required
def account(request):
    return HttpResponseRedirect(reverse('polls:user_account', args=(request.user.id,)))


@login_required
def user_account(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    # if request.user.id == user_id:
    return render(request, 'polls/account.html', {'user': user})
    # else:
    #     return render(request, 'polls/not_my_acc.html', {'user': user})


@login_required
def edit_account(request, user_id):
    if request.user.id == user_id:
        form = EditAccountForm(request.POST)
        set_initials(form, request.user)
        if request.method == 'POST':
            if form.is_valid():
                request.user.username = form.cleaned_data['username'] \
                    if form.cleaned_data['username'] != '' else form.fields['username'].initial
                request.user.email = form.cleaned_data['email'] \
                    if form.cleaned_data['email'] != '' else form.fields['email'].initial
                request.user.first_name = form.cleaned_data['first_name'] \
                    if form.cleaned_data['first_name'] != '' else form.fields['first_name'].initial
                request.user.last_name = form.cleaned_data['last_name'] \
                    if form.cleaned_data['last_name'] != '' else form.fields['last_name'].initial
                request.user.profile.bio = form.cleaned_data['bio']
                request.user.save()
                request.user.profile.save()
                return redirect('/polls/account')
        return render(request, 'polls/edit.html', {'form': form})
    else:
        return redirect('/polls/account/'+str(user_id))


@login_required
def create(request, user_id):
    if request.user.id == user_id:
        form = CreatePollForm(request.POST)
        if request.method == 'POST':
            if form.is_valid():
                text = form.cleaned_data['question']
                q = Question(profile=request.user.profile, question_text=text, pub_date=timezone.now())
                q.save()
                c1 = Choice(question=q, choice_text=form.cleaned_data['choice1'])
                c1.save()
                c2 = Choice(question=q, choice_text=form.cleaned_data['choice2'])
                c2.save()
                if form.cleaned_data['choice3'] != '':
                    c3 = Choice(question=q, choice_text=form.cleaned_data['choice3'])
                    c3.save()
                if form.cleaned_data['choice4'] != '':
                    c4 = Choice(question=q, choice_text=form.cleaned_data['choice4'])
                    c4.save()
                if form.cleaned_data['choice5'] != '':
                    c5 = Choice(question=q, choice_text=form.cleaned_data['choice5'])
                    c5.save()
                return redirect('/polls/account')
        return render(request, 'polls/create.html', {'form': form})
    else:
        return redirect('/polls/account/' + str(user_id))


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


@login_required
def delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user.id == question.profile.user.id:
        question.delete()
    return redirect('/polls/')


def set_initials(form, user):
    form.fields['username'].initial = user.username
    form.fields['email'].initial = user.email
    form.fields['first_name'].initial = user.first_name
    form.fields['last_name'].initial = user.last_name

polls/templates/polls/account.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="card">
<div class="card-body">
<nav class="navbar navbar-expand-sm bg-light">
    {% if request.user.id == user.id %}
  <ul class="navbar-nav">
    <li class="nav-item" style="margin-right:10px; margin-left:7px">
      <a href="/polls" style="color:white" class="btn btn-primary btn-block"> Feed </a>
    </li>
    <li class="nav-item" style="margin-right:10px">
      <a href="{% url 'polls:edit' user.id %}" style="color:white" class="btn btn-primary btn-block"> Edit profile </a>
    </li>
    <li class="nav-item">
      <a href="/polls/logout" style="color:white" class="btn btn-primary btn-block"> Log out </a>
    </li>
  </ul>
    {% endif %}
</nav>
    <div style="margin-top:20px">
    <h4>{{user.first_name}} {{user.last_name}}</h4>
        <h6>{{user.profile.bio}}</h6>
    </div>
    {% if user.profile.question_set.all %}
    <ul>
    {% for question in user.profile.question_set.all %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% if request.user.id == user.id %}
    <a href="{% url 'polls:create' user.id %}" style="color:white" class="btn btn-primary btn-block"> Create a poll </a>
    {% endif %}
    {% else %}
    {% if request.user.id == user.id %}
    <p>You didn't create any polls :(</p>
    <a href="{% url 'polls:create' user.id %}" style="color:white" class="btn btn-primary btn-block"> Create a poll </a>
    {% else %}
    <p>{{ user.first_name }} didn't create any polls :(</p>
    {% endif %}
    {% endif %}
</div>
</div>
{% endblock %}

polls/templates/polls/create.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="card">
<div class="card-body">
<h4 class="card-title">Create a poll</h4>

<form method="post">
{% csrf_token %}
<input type="hidden" name="next" value="{{ next }}">

{{ form|crispy }}

<button type="submit" class="btn btn-primary btn-block">Save</button>
</form>
</div>
</div>
{% endblock %}

polls/templates/polls/detail.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="card">
<div class="card-body">
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote" class="btn btn-primary btn-block">
</form>

{% if request.user.id == question.profile.user.id %}
<form action="{% url 'polls:delete' question.id %}" style="margin-top:10px">
    <input type="submit" value="Delete" class="btn btn-danger btn-block">
</form>
{% endif %}

Author: <a href="{% url 'polls:user_account' question.profile.user.id %}">{{ question.profile.user.first_name }} {{ question.profile.user.last_name }}</a>
<br>
    <a href="{% url 'polls:user_account' request.user.id %}">To my account</a>
</div>
</div>
{% endblock %}

polls/templates/polls/edit.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="card">
<div class="card-body">
<h4 class="card-title">Edit your account</h4>

<form method="post">
{% csrf_token %}
<input type="hidden" name="next" value="{{ next }}">

{{ form|crispy }}

<button type="submit" class="btn btn-primary btn-block">Save changes</button>
</form>
</div>
</div>
{% endblock %}

polls/templates/polls/index.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="card">
<div class="card-body">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<a href="{% url 'polls:user_account' request.user.id %}">To my account</a>
</div>
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="card">
<div class="card-body">
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}" >Vote again?</a>
    <br>
    <a href="{% url 'polls:user_account' request.user.id %}">To my account</a>
</div>
</div>
{% endblock %}